# fly.toml app configuration file generated for hiking on 2023-09-04T13:45:01-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "home2"
primary_region = "iad"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
