# fly.toml app configuration file generated for home2 on 2025-02-24T21:53:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'home2'
primary_region = 'iad'
console_command = '/rails/bin/rails console'

[build]
  [build.args]
    BUILD_COMMAND = "bin/rails fly:build"
    SERVER_COMMAND = "bin/rails fly:server"

[deploy]
  release_command = "bin/rails fly:release"

[env]
  PORT = "3000"
    
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
